services:
  spring-app:
    image: spring-app:latest
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-app-network
networks:
  spring-app-network:
    driver: bridge